53 feat adicionar função de migração
ceos-jr/orb pull request #57
Opened 2023-08-04 14:24 UTC by Lu1z-Gust4v0

# Descrição

Os seguintes pontos foram implementados:

- Função de migração do banco de dados 
- Função para fechar coneção com o banco de dados
- Função para testar coneção com o banco de dados
- Criar uma pasta para testes 
- Reescrever os testes utilizando o Testify
- Modificar configurações do linter
- Modificar o README.md para conter os novos comandos

Closes #52 
Closes #53 

## Tipo de mudança

- [ ] Bug fix (mudança não críticaque conserta uma issue)
- [x] New feature (mudança não crítica que adiciona uma nova feature)
- [ ] Mudança crítica (Concerto ou uma feature que pode quebrar funcionalidades antigas)
- [ ] Apenas mudança de documentação

# Como ele tem sido testado?

- [x] Testes unitários

# Checklist:

- [x] Realizei uma revisão do meu código
- [x] Eu comentei meus códigos, particularmente nas aŕeas mais difíceis
- [ ] Eu fiz as mudanças correspondentes na documentação
- [x] Minhas mudanças não geraram nenhum warning
- [x] Adicionei testes que comprovam que minha correção é eficaz ou que minha feature funciona
- [x] Testes unitários novos e já pre-existentes foram aprovados localmente
- [x] Qualquer mudança pendente na main branch já foi implementada nessa branch

2023-08-04 16:45 UTC, talDoFlemis approved these changes
aprovado, mas tem aquela parada dos erros que foi discutido 
![image](https://github.com/ceos-jr/orb/assets/33133120/f68f1e6c-f4b0-426c-891f-a40ca5194fef)

2023-08-04 19:48 UTC, talDoFlemis commented
> aprovado, mas tem aquela parada dos erros que foi discutido ![image](https://user-images.githubusercontent.com/33133120/258481589-f68f1e6c-f4b0-426c-891f-a40ca5194fef.png)

@Pedro6508

2023-08-04 19:50 UTC, Pedro6508 requested changes
# Remover CustomError antes de alastra-lo pelo código

2023-08-04 19:50 UTC, Pedro6508 commented on backend/utils/errorPattern.go
# O CustomError é um problema
O `CustomError` tem sido uma ideia problemática em geral, especialmente quando se trata do padrão de tratamento de erros. Ele adiciona pouca funcionalidade real ao código, ao mesmo tempo em que o torna desnecessariamente complicado. Além disso, a função para depurar erros que o CustomError foi destinado a cumprir em um determinado momento já não se justifica, uma vez que os testes unitários conseguem desempenhar essa função de maneira muito mais específica e eficiente.

Issue: #58

2023-08-05 01:21 UTC, Lu1z-Gust4v0 commented on backend/utils/errorPattern.go
Resolvido

2023-08-05 02:49 UTC, Pedro6508 approved these changes

2023-08-05 02:50 UTC, merged